/* eslint-disable @typescript-eslint/naming-convention */

export const assets = {
    images: {
        'filling/1.png': require('../assets/images/filling/1.png').default,
        'filling/10.png': require('../assets/images/filling/10.png').default,
        'filling/11.png': require('../assets/images/filling/11.png').default,
        'filling/12.png': require('../assets/images/filling/12.png').default,
        'filling/2.png': require('../assets/images/filling/2.png').default,
        'filling/3.png': require('../assets/images/filling/3.png').default,
        'filling/4.png': require('../assets/images/filling/4.png').default,
        'filling/5.png': require('../assets/images/filling/5.png').default,
        'filling/6.png': require('../assets/images/filling/6.png').default,
        'filling/7.png': require('../assets/images/filling/7.png').default,
        'filling/8.png': require('../assets/images/filling/8.png').default,
        'filling/9.png': require('../assets/images/filling/9.png').default,
        'game/bkg.jpg': require('../assets/images/game/bkg.jpg').default,
        'game/hand.png': require('../assets/images/game/hand.png').default,
        'game/sound_off.png': require('../assets/images/game/sound_off.png').default,
        'game/sound_on.png': require('../assets/images/game/sound_on.png').default,
        'interior/plant1.png': require('../assets/images/interior/plant1.png').default,
        'interior/plant2.png': require('../assets/images/interior/plant2.png').default,
        'interior/plant3.png': require('../assets/images/interior/plant3.png').default,
        'interior/zone_1_1.png': require('../assets/images/interior/zone_1_1.png').default,
        'interior/zone_1_2.png': require('../assets/images/interior/zone_1_2.png').default,
        'interior/zone_1_3.png': require('../assets/images/interior/zone_1_3.png').default,
        'interior/zone_1_4.png': require('../assets/images/interior/zone_1_4.png').default,
        'interior/zone_1_5.png': require('../assets/images/interior/zone_1_5.png').default,
        'interior/zone_2_1.png': require('../assets/images/interior/zone_2_1.png').default,
        'interior/zone_2_2.png': require('../assets/images/interior/zone_2_2.png').default,
        'interior/zone_2_3.png': require('../assets/images/interior/zone_2_3.png').default,
        'interior/zone_2_4.png': require('../assets/images/interior/zone_2_4.png').default,
        'interior/zone_2_5.png': require('../assets/images/interior/zone_2_5.png').default,
        'interior/zone_3_1.png': require('../assets/images/interior/zone_3_1.png').default,
        'interior/zone_3_2.png': require('../assets/images/interior/zone_3_2.png').default,
        'interior/zone_3_3.png': require('../assets/images/interior/zone_3_3.png').default,
        'interior/zone_3_4.png': require('../assets/images/interior/zone_3_4.png').default,
        'interior/zone_3_5.png': require('../assets/images/interior/zone_3_5.png').default,
        'interior/zone_4_1.png': require('../assets/images/interior/zone_4_1.png').default,
        'interior/zone_4_2.png': require('../assets/images/interior/zone_4_2.png').default,
        'interior/zone_4_3.png': require('../assets/images/interior/zone_4_3.png').default,
        'interior/zone_4_4.png': require('../assets/images/interior/zone_4_4.png').default,
        'interior/zone_4_5.png': require('../assets/images/interior/zone_4_5.png').default,
        'interior/zone_5_1.png': require('../assets/images/interior/zone_5_1.png').default,
        'interior/zone_5_2.png': require('../assets/images/interior/zone_5_2.png').default,
        'interior/zone_5_3.png': require('../assets/images/interior/zone_5_3.png').default,
        'interior/zone_5_4.png': require('../assets/images/interior/zone_5_4.png').default,
        'interior/zone_5_5.png': require('../assets/images/interior/zone_5_5.png').default,
        'lines/line1.png': require('../assets/images/lines/line1.png').default,
        'lines/line2.png': require('../assets/images/lines/line2.png').default,
        'lines/line3.png': require('../assets/images/lines/line3.png').default,
        'lines/line4.png': require('../assets/images/lines/line4.png').default,
        'lines/line5.png': require('../assets/images/lines/line5.png').default,
        'ui/arrow.png': require('../assets/images/ui/arrow.png').default,
        'ui/bar.png': require('../assets/images/ui/bar.png').default,
        'ui/button_no.png': require('../assets/images/ui/button_no.png').default,
        'ui/button_ok.png': require('../assets/images/ui/button_ok.png').default,
        'ui/buttons_bg.png': require('../assets/images/ui/buttons_bg.png').default,
        'ui/choice_bg.png': require('../assets/images/ui/choice_bg.png').default,
        'ui/house_icon.png': require('../assets/images/ui/house_icon.png').default,
        'ui/lock.png': require('../assets/images/ui/lock.png').default,
        'ui/money.png': require('../assets/images/ui/money.png').default,
        'ui/plus.png': require('../assets/images/ui/plus.png').default,
        'ui/progress.png': require('../assets/images/ui/progress.png').default,
    },
    particles: {},
    sounds: {},
    spines: {},
    atlases: {},
};

export const Images = {
    'filling/1': 'filling/1.png',
    'filling/10': 'filling/10.png',
    'filling/11': 'filling/11.png',
    'filling/12': 'filling/12.png',
    'filling/2': 'filling/2.png',
    'filling/3': 'filling/3.png',
    'filling/4': 'filling/4.png',
    'filling/5': 'filling/5.png',
    'filling/6': 'filling/6.png',
    'filling/7': 'filling/7.png',
    'filling/8': 'filling/8.png',
    'filling/9': 'filling/9.png',
    'game/bkg': 'game/bkg.jpg',
    'game/hand': 'game/hand.png',
    'game/sound_off': 'game/sound_off.png',
    'game/sound_on': 'game/sound_on.png',
    'interior/plant1': 'interior/plant1.png',
    'interior/plant2': 'interior/plant2.png',
    'interior/plant3': 'interior/plant3.png',
    'interior/zone_1_1': 'interior/zone_1_1.png',
    'interior/zone_1_2': 'interior/zone_1_2.png',
    'interior/zone_1_3': 'interior/zone_1_3.png',
    'interior/zone_1_4': 'interior/zone_1_4.png',
    'interior/zone_1_5': 'interior/zone_1_5.png',
    'interior/zone_2_1': 'interior/zone_2_1.png',
    'interior/zone_2_2': 'interior/zone_2_2.png',
    'interior/zone_2_3': 'interior/zone_2_3.png',
    'interior/zone_2_4': 'interior/zone_2_4.png',
    'interior/zone_2_5': 'interior/zone_2_5.png',
    'interior/zone_3_1': 'interior/zone_3_1.png',
    'interior/zone_3_2': 'interior/zone_3_2.png',
    'interior/zone_3_3': 'interior/zone_3_3.png',
    'interior/zone_3_4': 'interior/zone_3_4.png',
    'interior/zone_3_5': 'interior/zone_3_5.png',
    'interior/zone_4_1': 'interior/zone_4_1.png',
    'interior/zone_4_2': 'interior/zone_4_2.png',
    'interior/zone_4_3': 'interior/zone_4_3.png',
    'interior/zone_4_4': 'interior/zone_4_4.png',
    'interior/zone_4_5': 'interior/zone_4_5.png',
    'interior/zone_5_1': 'interior/zone_5_1.png',
    'interior/zone_5_2': 'interior/zone_5_2.png',
    'interior/zone_5_3': 'interior/zone_5_3.png',
    'interior/zone_5_4': 'interior/zone_5_4.png',
    'interior/zone_5_5': 'interior/zone_5_5.png',
    'lines/line1': 'lines/line1.png',
    'lines/line2': 'lines/line2.png',
    'lines/line3': 'lines/line3.png',
    'lines/line4': 'lines/line4.png',
    'lines/line5': 'lines/line5.png',
    'ui/arrow': 'ui/arrow.png',
    'ui/bar': 'ui/bar.png',
    'ui/button_no': 'ui/button_no.png',
    'ui/button_ok': 'ui/button_ok.png',
    'ui/buttons_bg': 'ui/buttons_bg.png',
    'ui/choice_bg': 'ui/choice_bg.png',
    'ui/house_icon': 'ui/house_icon.png',
    'ui/lock': 'ui/lock.png',
    'ui/money': 'ui/money.png',
    'ui/plus': 'ui/plus.png',
    'ui/progress': 'ui/progress.png',
};

export const Sounds = {};

export const Particles = {};

export const Spines = {};
